fix(app): provide the missing parameter to `inference()`
This fix resolves the following error message:
> TypeError: inference() takes 0 positional arguments but 1 was given

According to these docs[1], `inference()` receives the `model_inputs`
parameter from the SDK.

[1] https://docs.banana.dev/banana-docs/core-concepts/inference-server/
    serverless-framework/app.py#inference